### ISSUE TITLE
Rewrite sentence with proper grammar

### ISSUE THREAD

**Issue by Kazbin** [IdleLands/IdleLands#100]
"«Officers Beyond Donuts» released a self-titled album. They even manage to sell a few copies! [+891gold]"  
Should be:  
"«Officers Beyond Donuts» released a self-titled album. They even manage**d** to sell a few copies! [+891gold]"

**Comment by seiyria** [comment]
@AscendedGravity

**Comment by AscendedGravity** [comment]
Fixed in https://github.com/IdleLands/Custom-Assets/pull/5

**Comment by seiyria** [comment]
Thanks for reporting @Kazbin!
