### ISSUE TITLE
decide what item properties get implemented

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#104]
these properties are coming back:

* dance
* defense
* offense
* deadeye
* lethal
* silver
* power
* sentimentality
* vorpal
* aegis
* glowing

these are not coming back:

* absolute
* haste
* dancing (typo?)
* darkside
* anythingPercent
* anythingChance
* luck (typo)
* fear
* limitless
* parry
* punish
* royal
* sacred
* forsaken
* startle
* stealth
* sticky
* sturdy

these props need to be fixed:

* hpRegen -> hpregen
* mpRegen -> mpregen

**Comment by sedgwick** [comment]
"dancing" dance=1

It looks like there is a prefix-special that gives dance 1. Some items incorrectly applied dancing instead of dance. I'll fix those ones to use dance instead.

**Comment by seiyria** [comment]
the special prefix is fine, that one makes sense. yeah, fixing might be a better approach.

**Comment by sedgwick** [comment]
others:
* Aegis
* glowing

**Comment by seiyria** [comment]
those can stay in. I'll edit above.

**Comment by sedgwick** [comment]
All items in custom-assets repo have had the properties that are not coming back removed.
