### ISSUE TITLE
redefine party leave/disband rules

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#119]
- isBattleParty -> disband always after combat
- if party member length is 1 after pets/etc are removed, disband (bonecraft/necro pets might cause this)
- if a person leaves a party and there are <2 people, always disband (unless there is a combat going on) - this should allow the above case to work
- at the end of combat, remove all non-players from every party, and if <2 disband (in case of necro monsters)

**Comment by Anexes** [comment]
Are these still issues? I haven't heard anything about parties being weird recently, aside from the occasional choice to leave a party when you aren't in one.

**Comment by seiyria** [comment]
I don't know if they are, I haven't re-investigated.

**Comment by seiyria** [comment]
gonna call this one good
