### ISSUE TITLE
donate all resources button on inventory page

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#120]
should only show up if you have a guild. donate all current wood, ast, clay, stone

**Comment by Rovastus** [comment]
I would like to work on this issue. Is this issue still available ?

**Comment by boozledorf** [comment]
@Rovastus All Open issues in the Issue tracker are still available to be worked on.  Please feel free to work on this and submit a PR!

**Comment by seiyria** [comment]
Yep! Feel free.

**Comment by Rovastus** [comment]
Ok, then I will work on this issue.

**Comment by boozledorf** [comment]
Closed in #145

**Comment by boozledorf** [comment]
Closed in #145
