### ISSUE TITLE
discord message audit log for guild

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#121]
when upgrading a building, donating resources, promoting a member, etc - a discord message should be sent to the guild channel if it exists.

Messages sent specifically:
- member joins
- member applies
- member leaves
- member is promoted
- member is demoted
- a building is upgraded
- a raid is started
- the tax rate changes

It would also help to have a section in the README for how to set up/test discord integration!

These messages should _only_ be sent if the crier building is active! The messages should say who initiated the action, as well.

**Comment by ghost** [comment]
I will try and take a look at this.

**Comment by ghost** [comment]
**Updated issue description:**

When upgrading a building, donating resources, promoting a member, etc - a discord message should be sent to the guild channel if it exists.

Messages sent specifically:
* member joins
* member applies
* member's application has been accepted
* member's application has been denied
* member leaves
* member is promoted
* member is demoted
* member was kicked
* a building is upgraded
* a building was toggled on/off
* a raid is started
* the tax rate changes
* a guild's MOTD has been updated
* a guild's application type

These messages should _only_ be sent if the crier building is active!
The messages should say who initiated the action, as well.
Also, look into making upgrading crier building sent more and/or more detailed messages into the guild channel.

It would also help to have a section in the README for how to set up/test discord integration + update the overall content of README and its readability!
