### ISSUE TITLE
somehow, discord tag unique check does not work

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#126]
two people can set the same discord tag, which should not be allowed.

**Comment by DrKain** [comment]
It looks like it just adds verified if the user doesn't have the role, There's no handle if the user is already verified. Am I reading this right?    

  
https://github.com/IdleLands/IdleLands/blob/b5e9046876ee8277520552d49d5d71c0c81c01f0/src/server/core/game/discord-manager.ts#L148-L153
