### ISSUE TITLE
PVP battles can happen between parties whose party levels are >5 levels apart.

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#127]
[https://github.com/IdleLands/IdleLands/blob/master/src/plugins/events/events/BattlePvP.js#L43](url)

`.reject(p => p.level < player.level - SETTINGS.pvpBattleRange || p.level > player.level + SETTINGS.pvpBattleRange)`

Is, I believe, supposed to be:

`.reject(p => p.party.level < player.party.level - SETTINGS.pvpBattleRange || p.party.level > player.party.level + SETTINGS.pvpBattleRange)`

The change being **p.level -> p.party.level** and **player.level -> player.party.level**

That seems to be the correct syntax, though I'm not 100% certain.

**Comment by SecondSkinPT** [comment]
Thanks for this update!
