### ISSUE TITLE
rename pet crystal to just crystal

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#135]
gacha reward, possibly the interface will need some renames

**Comment by ZeroHands2Feet** [comment]
#135 https://github.com/IdleLands/IdleLands/blob/bfdd82d8ae4f2c211b1a36ca797d9b4f18c30ae3/src/shared/interfaces/IGacha.ts#L154-L168

  [GachaReward.CrystalGreen]: 'Crystal (Green)',
  [GachaReward.CrystalYellow]: 'Crystal (Yellow)',
  [GachaReward.CrystalRed]: 'Crystal (Red)',
  [GachaReward.CrystalBlue]: 'Crystal (Blue)',
  [GachaReward.CrystalPurple]: 'Crystal (Purple)',
  [GachaReward.CrystalOrange]: 'Crystal (Orange)',
  [GachaReward.CrystalAstral]: 'Crystal (Astral)',


  [GachaReward.CrystalGreen5]: 'Crystal (Green x5)',
  [GachaReward.CrystalYellow5]: 'Crystal (Yellow x5)',
  [GachaReward.CrystalRed5]: 'Crystal (Red x5)',
  [GachaReward.CrystalBlue5]: 'Crystal (Blue x5)',
  [GachaReward.CrystalPurple5]: 'Crystal (Purple x5)',
  [GachaReward.CrystalOrange5]: 'Crystal (Orange x5)',
  [GachaReward.CrystalAstral5]: 'Crystal (Astral x5)',

**Comment by CyberOnion** [comment]
Made a PR request with the updated information
