### ISSUE TITLE
PVP Battles are extremely rare for parties at higher levels

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/IdleLands#143]
#127 #40

Currently, party PvP battles are very rare at the higher end of the player base. The PVP rate is much lower than it used to be. A flat +/- 5 average level that is currently implemented has not allowed many battles.

- Possibly scale `SETTINGS.pvpBattleRange` once  according to the party level?
- Do multiple passes while increasing the valid battle range?
- With no match, possibly initiate a PvE combat instead? Related: #142 on tracking stats.

**Comment by kitocole** [comment]
PvP battles are extremely low for any level in my experience. Both my level 29 and level 15 chars havent gotten into a PvP battle today and yesterday (9/12,13). I havent seen a PvE battle at all today either.

**Comment by seiyria** [comment]
pvp battles previous threw errors, I'll fix this and possibly expand the range.

**Comment by seiyria** [comment]
stat tracking will no longer fire erroneously as it is opt-in for each event. I'm not going to initiate a PvE battle from PvP at this time until I can simplify the code paths for pvp. lets see if this works out a bit better first.
