### ISSUE TITLE
Guild invites/applications fail to show any user details of an offline invitee/applicant

### ISSUE THREAD

**Issue by EricChiz** [IdleLands/IdleLands#149]
Invite/application line still contains [Deny][Accept] for applications and [Rescind] for invitations, but it cannot be determined which user is being accepted, denied, or uninvited as no name or any other detail is displayed.

**Comment by seiyria** [comment]
Displayed for what purpose? I've left it ambiguous in the toast messages but all of that data should be available somewhere, I'm just not sure what you're looking at specifically.

**Comment by EricChiz** [comment]
![Example of Members tab of Guild area](https://user-images.githubusercontent.com/20449164/65707389-6f454580-e05a-11e9-9dfc-62e07ff04711.png)

Invitees on lines 1 and 2 are online, are shown.
Invitees on lines 3 and 4, and Applicant on line 5, are offline, and are completed devoid of any details at all, including name or any sort of identifier at all.

To have intentionally "left it ambiguous" to this extent seems a bit much.

**Comment by seiyria** [comment]
Interesting, is this present in other themes as well? It's likely this is a theme issue. Invites always have the name of the person attached to them so that should at least always be displayed.

**Comment by EricChiz** [comment]
It's like this in every theme. Opening the browser DOM inspector shows that these lines contain absolutely no user information.

**Comment by seiyria** [comment]
Fair! Thanks for confirming. This would be pretty easy to fix so I'll leave this open for anyone who wants it. If it's not fixed in a week or so, I'll sort it out when I have time. Thank you!

**Comment by EricChiz** [comment]
A populated invite line, outerHTML:
`<ion-item _ngcontent-c3="" class="item-label item md in-list ion-focusable hydrated"><!----><ion-label _ngcontent-c3="" class="sc-ion-label-md-h sc-ion-label-md-s md hydrated"><h3 _ngcontent-c3="" class="vertical-center"> (USERNAME HERE)<!----><span _ngcontent-c3="">, (USER TITLE HERE)</span></h3><p _ngcontent-c3="" class="vertical-center ion-margin-start"><ion-badge _ngcontent-c3="" color="secondary" class="ion-color ion-color-secondary md hydrated"><!----><span _ngcontent-c3="">11★</span>369</ion-badge> &nbsp; SandwichArtist </p></ion-label><!----><!----><!----><ion-button _ngcontent-c3="" slot="end" class="md button button-small button-solid ion-activatable ion-focusable hydrated">Rescind</ion-button></ion-item>`

An offline-user invite line, outerHTML:
`<ion-item _ngcontent-c3="" class="item md in-list ion-focusable hydrated"><!----><!----><!----><!----><ion-button _ngcontent-c3="" slot="end" class="md button button-small button-solid ion-activatable ion-focusable hydrated">Rescind</ion-button></ion-item>`
