### ISSUE TITLE
brainstorm ways of spreading out player actions

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#153]
right now everyone always takes a turn every 5 seconds, but that's not working out so well. possibly, make everyone take a turn every 5 seconds based on their login time (to stagger the load), and instead of updating all players post move, just update them one at a time.

**Comment by sidawson** [comment]
I'm working on something that will help enormously with this (reduce load in general), although I think 5 secs based on login is sensible (and relatively easy).

I'll get back to working on it once I finish with connections.

**Comment by seiyria** [comment]
no problem, good thing you mentioned or I would have started on this. I'll hold off on this for now.

**Comment by sidawson** [comment]
Key load spike is still at deploy (the Travis issue), but we're also getting mass disconnections (which will be similar). All these things are tied together. 

If you can stagger update times relatively easily though, I'd say go for it.  That's a necessary future change.

**Comment by seiyria** [comment]
then I'll give it a go, it should be rather trivial

**Comment by sidawson** [comment]
Update every second. List of players against game state with "login % 5", update the list that matches "current time % 5"' yep. I'd call that trivial :)

**Comment by sidawson** [comment]
On the off chance you haven't started this, suggest storing some variant of "tick number" (0-4) against the player, so it's easier to remove them from the appropriate update list on gamestate.delPlayer (no point in searching all five lists for them, that just adds to load at a key time).

**Comment by seiyria** [comment]
wasn't even going to do that that way, I was just going to store a timestamp for "next move" and if the player can't take a turn, they're skipped.

**Comment by sidawson** [comment]
On balance, a reasonable approach. Slightly less efficient, a bit less complex.

**Comment by SecondSkinPT** [comment]
Alright, I've been trying to login via Facebook and I can't seem to get in. I wanted to use the Facebook login being that it is my for my business. I'm trying to get some assistance on the issue. Any help with this?

**Comment by seiyria** [comment]
We'll call this one good for now.
