### ISSUE TITLE
Pet stats don't appear to update when changing equipment on them manually

### ISSUE THREAD

**Issue by sidawson** [IdleLands/IdleLands#158]
Certainly the left hand pet overview doesn't update. 

**setup**
* Player has body equipment A
* Pet has body equipment B. 
* A has very different stats from B.

**to repro**

1. Swap A (from player)->pet inv
2. Swap B (from pet)->pet inv 
3. Swap A from pet inv->pet

Pet overview stats remain the same as they were when pet had item B.

**Comment by seiyria** [comment]
Thanks. I probably just need to do a pet.recalculateStats in a few places. Should be an easy fix.
