### ISSUE TITLE
Blank page on Safari

### ISSUE THREAD

**Issue by Hipska** [IdleLands/IdleLands#160]
The site doesn't even work on Safari.
It seems like a simple 3 column layout, how can it be that it shows just an empty page?

**Comment by seiyria** [comment]
I believe safari does not support es6 proxy. That will cause it to fail. Use a better browser.

**Comment by Hipska** [comment]
What about notifying the user and/or providing a fallback?
Use a better front-end.

**Comment by seiyria** [comment]
There is no fallback or polyfill available for proxies. The most I can say
is "if this page is loading for too long you need to use a different
browser."

**Comment by Hipska** [comment]
That would already be something more useful. Although, I noticed to have a 'Loading...' message shortly, and after that, the page goes blank. So there might be an issue.

**Comment by seiyria** [comment]
https://github.com/IdleLands/Play/issues/95 I'll look into something.
