### ISSUE TITLE
New Choice Personality

### ISSUE THREAD

**Issue by boozledorf** [IdleLands/IdleLands#174]
To complement Affirmer, Denier, and Indecisive

- If an option has at least one choice other than "Yes", "No", and "Compare", randomly choose between all remaining choices (if there's only one left, choose it always)
- If an option only has "Yes" and "No" choices, then sample between those

The current effects would be:
- Always Double Down on Gamble events
- Always sell items found (not from merchants)
- Always purchase and send merchant items to inventory
- Probably something else that I'm blanking on

It just needs a name and an implementation.  Naming suggestions would be apprecaited!

**Comment by CyberOnion** [comment]
I have been thinking about it. I think it would be better to do multiple personalities instead of just one.
For example: 
Merchant - auto sells items/buys items and send it to inventory.
Gambler - Doubles down on all gamble events

**Comment by seiyria** [comment]
Having it be multiple personalities means there would need to be significant drawbacks to each one, as well as having only one active at a time. Having them all in one is it's own drawback IMO.
