### ISSUE TITLE
Overlapping tooltips

### ISSUE THREAD

**Issue by Kazbin** [IdleLands/IdleLands#182]
As you can see in the image, on hovering over e.g. the sell icon there is an extra tooltip behind the other and I do not think that it is supposed to be that way.
![image](https://cloud.githubusercontent.com/assets/2299735/18608996/85c82d1e-7cf7-11e6-8a58-8836bbd3c4a0.png)

**Comment by seiyria** [comment]
It isn't, but I don't have any control over it at this time.
