### ISSUE TITLE
somehow people are getting into undefined (map)

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#184]
happening on norkos -8 and leviathan mountain

**Comment by sedgwick** [comment]
I checked both maps, and I haven't found any locations where the blocking layer would let a player out.

**Comment by seiyria** [comment]
that's weird then. what's even more strange is that they _should_ be getting teleported to norkos if they go to an invalid place. I'll have to look more at it.

**Comment by seiyria** [comment]
Uhrl: hello ! seems i have a problem with the map. I entered Leviathan Mountain (archer side) and map is black :/ but my hero is moving

not sure what's going on. will investigate more later.

**Comment by sidawson** [comment]
The map black but hero moving sounds like a VERY common thing I see. The map just hasn't loaded from CDN. Clicking two, three or sometimes more of the other menu items (overview them collectibles then achievements etc) then back to map usually sorts it out.

Usually this happens with you seeing the old map, not the new one, but occasionally it's black. Same "fix" gets it working again.

May or may not be related.

**Comment by seiyria** [comment]
It's not always CDN. Sometimes they're literally getting steps on undefined, which wouldn't happen. Additionally, the problem has happened several times with levi mountain now so I'm concerned that something is wrong with the transit.

**Comment by sedgwick** [comment]
> Uhrl: hello ! seems i have a problem with the map. I entered Leviathan Mountain (archer side) and map is black :/ but my hero is moving

>not sure what's going on. will investigate more later.

Travis would catch a bad staircase destination, and I double checked them as well for any weird problems and no weird issues/properties with archer staircase. I did notice that n-7 staircase up to n-6 has a blank property, but that is not the case for archer stairs. http://puu.sh/rfW4m/70df92dc84.png

**Comment by seiyria** [comment]
empty props shouldn't break anything.

**Comment by seiyria** [comment]
I did notice that if I hover over archer, it doesn't have a type (which would normally be set to Trainer) http://global.idle.land/maps?map=Leviathan%20Mountain&x=0&y=0

compared to, say, bard http://global.idle.land/maps?map=Bard%20Island%20-1&x=0&y=0

not that it should have anything to do with it.

**Comment by sedgwick** [comment]
That's weird, as it is set properly and I don't see any difference in Tiled between the two, other than Name.
http://puu.sh/rfWKW/3977a595bd.png

**Comment by seiyria** [comment]
nice. looks like some oddity that I will have to investigate manually then.

**Comment by sidawson** [comment]
For the record, I don't think the maps not loading is a CDN issue. Broken CDN gives you old data. Each map has a diff url. If we were getting old _versions_ of maps, that would be CDN. Blank or nothing loaded doesn't smell like CDN problems to me. However, until I get Play up & running, I can't dig in, find & fix it. More important things first.

**Comment by AscendedGravity** [comment]
Chrome console log when opening the map in the Leviathan's

![image](https://cloud.githubusercontent.com/assets/439533/18619926/c4650e26-7dcd-11e6-92de-cf3b75800884.png)

**Comment by seiyria** [comment]
Again, definitely not the CDN. I fixed this issue last night when developing the global maps solution.

**Comment by sidawson** [comment]
Jesus fuck, dude. We're agreeing with each other.
