### ISSUE TITLE
Mapceptional Maps

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/IdleLands#204]
Come up with a new list of maps that should rate a Mapceptional achievement. Current mapceptional maps are Norkos Secret -1 and Norkos Dungeon -11, so going off this small list it's clear that very hard to reach maps and important maps qualify.

**Comment by seiyria** [comment]
Correct. I try to make them maps that are the farthest out or are otherwise interesting. Ones that people don't get to very often.

**Comment by sedgwick** [comment]
* fate lake
* fate pools -1 because im sorry for anyone who enters.
* merchant's guild
* the astral plane
* elemental plane -3
* holiday maps?
* dt+1, grats on climbing the tower.
* hall of heroes, thanks for visiting.

**Comment by seiyria** [comment]
think it should be fate pools -2, but other than that, I like this list

**Comment by sedgwick** [comment]
Cruel but doable, and it does give a reason to dive deeper into the pools.
