### ISSUE TITLE
Ascending

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#222]
Old issue can be found here: https://github.com/IdleLands/IdleLandsOld/issues/417

Here is how ascending will work: You will get to a level past 100, and you'll have the option to ascend. When you ascend, your current item score, gold, and level will be recorded as a permanent stat. You will get achievements based on how high each of these are (so you can ascend twice at level 100, or once at level 200 for a similar effect). Perhaps, though, you'll have to hit max level each time

This may result in ultimately making the current max level 100. Sorry, if you go past 100, we will figure something out (possibly just giving you a forced ascension and giving you those bonus levels).

Now, since your stats are all recorded permanently, you'll get achievements for your gains. Obviously, the game-able one is gold. The simple answer is that you get no permanent gold ascension bonuses if you give it all away first. You could do the same with equipment, but it results in the same thing - no equipment bonuses. Level is not really game-able.

Now, how this will work. Ascension bonuses will grant **significant** boosts for subsequent playthroughs. Suppose you bank 1mil. That would probably correspond to +10% gold gained from all sources. These achievements would also be exponential, so 1m, 10m, 100m - 30% gold from all sources. Probably a title way, way down the line.

After ascending, your gold is removed.

For equipment, it would probably start at 100k (since items generally top off around there). Then 1m, 10m, etc. And this would result in item equip multipliers as well as static bonuses. Titles down the line. This would also increase your maximum item score (+100% every tier).

After ascending, you start with no equipment. Maybe newbie gear, but TBD.

Levels are where it's at, though. This is where the real bonuses come in. Probably, this achievement would progress differently as the scale is a bit different. Maybe, a static progression: 100, 300, 500, 700, 900, 1100, etc. Titles periodically, like usual. But this gives you other real bonuses, too:
- an xp boost (maybe 5% per 100 levels)
- a `soul` slot which is synced with your pet
- the ability to multiclass at a certain ascension level
- the ability to breed pets at a certain ascension level
- the ability to access new parts of the map at a certain ascension level
- a max level increase of 50 per ascension level (meaning you can go longer without ascending)
- being able to be attached to an item while online (as a suffix, such as "of Seiyria, the Avatar" or whatever your current ascension title is)
- new skills for every class at a certain ascension level (of course, these would be balanced in, and possibly would grant new skills between normal draughts).
- get to keep X items (where X is a certain ascension (probably the level 500 one) and every 2 ascensions after that, you get to keep another item) [possibly implemented as a pet]

Additionally, all players should get a buff [tbd, needs implemented] when someone ascends. It should increase xp/gold gain.

Pet levels are also reset.

**Controversial Items**:
- Should your collectibles be wiped? If so, the obvious perk is that we can also require certain collectibles to ascend. Of course, this means you'd have to re-find all of the collectibles.
- Statistics will of course be preserved, but this does not mean all of your achievements will persist. A small handful of them will have to be re-obtained (Levelable, for example). 
- Should there be a legendary quest that needs to be done every time? Of course, this will require quests to be implemented, which is a ways off (this may even come first). Something to think about, still.

**Comment by sedgwick** [comment]
The only way I feel wiping collectibles would be reasonable is if you get some kind of credit for what you already collected. It would also give a reason to bother with basic collectibles during your leveling time, since a higher count could give some kind of bonus. But because there is a limit to how many collectibles you can pick up during an ascension (however many happen to be in the game at the time), I do not believe an exponential amount for the achieve would work. And I am not quite sure what the reward should be, since it should relate back to collectibles earned.

I think starter gear would be nice over nothing, since the starter items are never seen again after you replace them now.

**Comment by seiyria** [comment]
I think we could do a "collectible" ascension too. Maybe doing so would unlock the personality that makes you gravitate towards collectibles.

**Comment by Anexes** [comment]
As someone who has gone *way* out of his way to get as many collectibles as possible, 200 is a ridiculously huge number. Most players probably won't have 75 by the time they hit level 100. Other than that, I agree with the collectibles/gravitation thing.

I agree with Sedg on wiping collectibles. Maybe each class gets a bonus based on how many of that class's collectibles you've found? Could be stats? Maybe they could be additional requirements for unlocking the new ascended spells. I want there to be *something* special about the class-specific lore collectibles...Doesn't feel right that they're worth nothing more than +1 collectible and a mildly interested "Hm."

I just now realized what you meant about being attached to an item. Would that be like...gear that other people would pick up? Would it give stats like a typical suffix? Would the stats scale with your ascension levels/stats? That'd be badass. I love the idea of only strong players being able to wield gear associated with an ascended player. I *extra* love the idea of a player having so many ascension levels that gear associated with them is too strong for non-ascended players to equip. It'd be like gods worshiping gods xP

**Comment by sedgwick** [comment]
In addition, there aren't even 200 collectibles in the game right now. current count is 191.

**Comment by seiyria** [comment]
yeah, so what would happen is you count the collectibles you find in one playthrough, wipe them, re-find them, and those would be added to he next ascension count. so you could get up to 382 on the next ascension. It's not a unique count.

**Comment by seiyria** [comment]
By attached to the item, I mean they would get their own suffix (or possibly prefix, also) and it would have certain stats based on something. I have no idea how this would work yet, but it would be something based on the ascension count, for sure.

**Comment by seiyria** [comment]
PvP would have to start using gear score to match, instead of level.

**Comment by seiyria** [comment]
Possibly grant access to prestige classes, like Lich.

**Comment by Anexes** [comment]
@seiyria  I'd be interested in seeing how gear score matching would compare. Before actually changing it, could I get some data? If you could log both parties' gear scores and which party won for a bunch of combats, even if it's just in a "party1score party2score winner\r" format, I could toss it into a spreadsheet and make some charts and graphs. If you included party level, I could compare the two matching types.

I don't know how much any of that would help you, but I'd like to think I could make some balance suggestions, or at least provide the data for someone better at this stuff than I am.

**Comment by seiyria** [comment]
I'm not actually going to make that change for a while, so we can talk about it later.

**Comment by seiyria** [comment]
Collectibles will still be wiped, but there should be a permanent list of things you have collected at one point. They should be greyed out (or given a layer of opacity) in Play and Global to signify that you have not collected them in this lifetime.

**Comment by sedgwick** [comment]
Also, a personality to gravitate towards stairs, just like the collectible one mentioned above. Would help those who make it a goal to ascend more than once on their quest to get more collectibles/bosses/etc.

**Comment by seiyria** [comment]
Some basic ascension has been implemented, but there is a lot of work to be done yet. That will happen in the future.

**Comment by boozledorf** [comment]
With some of the new properties that items can have that Kookie is developing, it might be time to start adding that some items (possibly boss-drop items only so you don't just hoard stuff with the right prefix/suffix) have a property that lets them persist between ascensions.

The mechanic would be that when ascending, items without this property would be wiped, but items with this property would have their has_equipped property turned off, so that you can't wear it immediately, you have to get to the point where your item score would be strong enough to wear it anyway.

**Comment by seiyria** [comment]
As per the commit above, I've added 3 pets that can preserve 1 item each upon ascension. I'm still open to the way described above for item preservation but I wanted to add this as well.

**Comment by seiyria** [comment]
The only other open issue that I think will get implemented is pet breeding, and it has it's own issue #162, so this one can finally be closed. 🎉
