### ISSUE TITLE
Cant log in!

### ISSUE THREAD

**Issue by LittleTwobig** [IdleLands/IdleLands#293]
Found this game looking to play something new but for the life of me i cannot log in into the game! Igot as far as creating my ingame name and pressing the play idlelands button but nothing happens when i do

![game](https://user-images.githubusercontent.com/62771692/77797255-01d89880-702e-11ea-9823-ce7697bcfa0a.PNG)

not even sure if the image i dropped here is working but in case it doesnt it shows the Welcome to IdleLands!It's an idling game like you've never seen. Or maybe you have, if you've been here before.
 the beneath this is Welcome to IdleLands, LittleTwoBig! You are a level 14/100 Generalist. Your adventure will begin in Norkos. and the play idlelands! beneath it which is something i can click but when i do nothing happens no loading screen no buffering or something it simply doesnt do anything yet seems im lvl ing someway or another as im lvl 14/100 hahahah and each time i reload it i get a few lvls more but thats it. Is there something i need to do to play it? or disable something/enable something? any help would be greatly appreciated. thank you

**Comment by seiyria** [comment]
It is known and being looked into. There is a weird server issue that's been afflicting the game for the last week or two and it is being debugged as we have time to do so.
