### ISSUE TITLE
battles occasionally don't show

### ISSUE THREAD

**Issue by sidawson** [IdleLands/IdleLands#299]
Clicking the battle link from the overview screen results in a blank page (menu at the top, blue "copy" button, nothing else).

console log shows:

't' not found in precompile array.  To ensure all components referred to by the RouterConfig are compiled, you must add 't' to the 'precompile' array of your application component. This will be required in a future release of the router.

Going back to overview & reclicking link results in repeats of the log error (one more for every time the link is clicked), as does refreshing the page while on the battle url.

**Comment by seiyria** [comment]
Unfortunately that error has nothing to do with it. Is the battle older
than two hours?

**Comment by sidawson** [comment]
Yeah, I've seen that "'t' not found..." error happening other places too. Just interesting that it occurs (also) directly as a result of clicking the battle link.

Can't say whether battle is > 2 hours old. Reasonably sure I've seen this problem with very recent battles (saw that happen the other day), but current Adventure Log only has ~15 entries for the last 24 hours. Which is odd.

Will wait until I get another battle, to verify, then report back.

**Comment by seiyria** [comment]
Thanks. That issue happens any time there is a state change so it's not
particularly noteworthy. It'd be away if I updated angular but that's a
ways away, if at all.
