### ISSUE TITLE
combat is fucked

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#30]
somehow sedgwick got in combat with a level 1 mirror monster, and also somehow he got no xp/gold from a monster battle

http://puu.sh/qFdlp/581f8d21ee.png
http://puu.sh/qFdnD/380f3c7afa.png

it may be a monster issue or something but it needs to be looked at.

sedgwick also found himself in a solo party again

also implement mirror monsters and set their level appropriately

**Comment by seiyria** [comment]
Lets call this good for now. No solo parties today, xp/gold was solved (thanks Tniro).

**Comment by sedgwick** [comment]
http://puu.sh/qGXmz/cb1b012a91.png

Had a solo battle, joined and left a party that was disbanded, then no other events. this isn't the name of either of the other groups.

**Comment by sedgwick** [comment]
http://puu.sh/qI3J3/4ce92d7782.png

Now it's asking me if I want to leave a party with no party displayed. Going through adventure log, I did not see an event for this party.

**Comment by seiyria** [comment]
I tried seeing if maybe hiding the battle party would work, as it might
have just been a weird side effect. You do still have a solo party in this
case, it's just hidden.

**Comment by seiyria** [comment]
this doesn't seem to affect much, don't care too much anymore. if it causes problems again I'll fix it but for now I'm just going to play the "hide and ignore it" game
