### ISSUE TITLE
Feature: Quick Sell Inventory

### ISSUE THREAD

**Issue by Vandivier** [IdleLands/IdleLands#322]
On this screen: https://play.idle.land/gear/inventory

Add an advanced accordion that lets you quick sell by quality

It can also have a quick salvage

**Comment by DrKain** [comment]
Already in the game. There should be a [menu](https://github.com/IdleLands/IdleLands/blob/master/src/client/app/inventory/invactions.popover.ts#L8-L18) at the top right of the inventory screen to salvage/sell all items
