### ISSUE TITLE
Stuck in Cabran Dungaon-1

### ISSUE THREAD

**Issue by EnderEvee** [IdleLands/IdleLands#329]
I am stuck in Cabran Dungeon-1 as a lvl 45. I used the teleporter south of the black dragon king and ended up there as an unAscended player.

**Comment by seiyria** [comment]
use a teleport scroll to get out

**Comment by EnderEvee** [comment]
im completely new how and where do I get one of those

**Comment by EnderEvee** [comment]
> use a teleport scroll to get out

how and where do I get one of those
