### ISSUE TITLE
play.idel.land/home keeps putting me in a loop

### ISSUE THREAD

**Issue by Seeker-Of-Knowledge** [IdleLands/IdleLands#336]
It saves the data base is down. Sometimes it tells me to log in but when I try nothing happens.

I have waited over 3 hours trying to get this game working. What should I do?

https://user-images.githubusercontent.com/75857627/150533036-2052b0b8-3531-44f3-9149-993481ef550a.mp4

**Comment by seiyria** [comment]
The server is lagging or down. You must wait, that's really it.
