### ISSUE TITLE
stoned ("like a rock") personality

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#36]
personality that makes it so you do not move (also get no xp for moving)

maybe make it so it turns off events, and definitely does not teleport you if you get in a party

maybe instead call it "unconscious" and have it mark you afk (visible in chat)

cannot be selected by fate pools

**Comment by sedgwick** [comment]
Another idea I had for this was Camping. Maybe a little campfire sprite so you can see it's someone who is not moving for a reason.

**Comment by seiyria** [comment]
that's definitely the neatest idea I've heard so far... want to add a campfire sprite to the list?
