### ISSUE TITLE
Bards using way too much mana

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#375]
Mew told me that bard songs (as well as pretty much all AoE spells,) were deducting their mp cost per target, so I asked him to get me a pastebin. His raven did indeed spend 100% of its mp (13,675 mp) after casting You Shant Get Away, and was unable to cast for the rest of the fight. The enemy also had a bard (a player no less, a rare sight indeed,) who was also spending mp proportional to the number of targets, but he only had rank 1 of the spells so he was able to cast through the fight.

And in the case of the buff spells (Our Hearts Ignite, There Is No Escape, and Light From The Stars) it's deducting the cost twice; once for each buff. With a 4-player party, the caster ends up paying 8x the mp cost for the three buff spells.

Combat log: https://justpaste.it/yoa4

Mew said you said it was intentional, but I have a feeling he misunderstood or didn't give enough information. These spells are costing obscene amounts of mp, such that once you're past level 50, even stacking int would only get you a small handful of spells per combat.

Mew said to look out for food fight as well, but I expect it's all AoE spells. After looking at Pirate Shanty, I think that's also deducting 2x cost when the target is a pirate. Generally speaking, it seems like every call for super.cast deducts the cost from whichever resource pool it's using.

Easy solution: Divide the cost by the expected number of targets (typically 4.)
Probably also easy solution: Subtract the cost in preCast rather than in spell.cast. That way, if you want it to cost more per target, you can always put it in the _.forEach loops, but if you don't, you can just put it at the beginning/end. (I thought that might mess with BottleToss, but you gave that one a cost of 0 and handled it manually in shouldCast/preCast, so it wouldn't matter.)

**Comment by seiyria** [comment]
subtracting in `preCast` means every spell has to remember to do it on their own. I would much rather adjust the mp cost of every spell.

**Comment by Anexes** [comment]
@seiyria If the cost were just reduced, I think it would let you cast the spell as long as you could afford to cast it on one person, even if you then went and cast it on ten people. Perhaps, rather than putting the cost deduction in `preCast`, you could count the number of targets in `shouldCast` and only return true if `caster.stat >= cost * numTargets`? I suppose each spell would still have to have that written in...

I don't know. I'm tired. And it's late, so I don't even feel a little bit bad about it. I'm sure you'll find a solution far faster than I will, but I'll try to think about it anyway :P

**Comment by MewYi** [comment]
Combat log of sandwich artist's food melee showing the same problem: https://justpaste.it/yp5e
