### ISSUE TITLE
Boss collectible rarity property not working properly

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/IdleLands#376]
Found one of the Merchant's Guild collectibles, which is set in boss.json as godly rarity. It shows up in the collectibles tab as guardian rarity.

**Comment by Anexes** [comment]
@sedgwick Is this still an issue? Could you tell me which collectible it is?

**Comment by Anexes** [comment]
@sedgwick Oh, well, looks like all of them. I have Large Decorative Key and Solid Gold Amulet and both are guardian. Golden Ticket is basic; not sure if it's supposed to be.

**Comment by Anexes** [comment]
@seiyria Could it be because it's iterating through `boss._collectibles` rather than `boss.collectibles`? ([here](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/events/events/BattleBoss.js#L71))

**Comment by seiyria** [comment]
No. The array is copied onto the boss. If it wasn't correct they wouldn't
drop at all.

**Comment by Anexes** [comment]
@seiyria Does the _ do anything in `boss._collectibles`? Is it part of the identifier? Or is it just ignored? I looked around to see if underscores did anything in identifiers, but everything said they were just a normal character. It seems to work, but I don't understand how `_collectibles` could return the right thing.

**Comment by seiyria** [comment]
https://github.com/IdleLands/IdleLands/blob/d8d6977dcf8a5741aed531731dd7c3702d47d723/src/shared/monster-generator.js#L53

**Comment by Anexes** [comment]
@seiyria Ahh, thanks.

**Comment by seiyria** [comment]
seems this is fixed
