### ISSUE TITLE
Renamed collectibles can be found again

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/IdleLands#377]
http://puu.sh/rmJqj/a0efc37e96.png

After the draygons were changed to dragons, it became possible to find the renamed collectibles again. It's possible (unlikely, but I don't want to say it will never happen again) that we may need to rename another collectible(s) and it could lead to many extra finds for players.

http://puu.sh/rmJqj/a0efc37e96.png

**Comment by seiyria** [comment]
Any chance you know what collectibles were renamed? I know just that one, but I don't remember any others.

**Comment by sedgwick** [comment]
* Red Dragon Scale
* Green Dragon Scale
* Undead Dragon Scale
* Black Dragon Scale
* Silver Dragon Scale
* Mama Red Dragon Scale

All of these had their name updated, so it's possible "Draygon" versions of their collectibles are still in some player's lists. I myself have mama red draygon scale and black draygon scale.

**Comment by seiyria** [comment]
Solution: check player collectibles against the existing set and remove ones that aren't available.
