### ISSUE TITLE
party = stuck?

### ISSUE THREAD

**Issue by Reloecc** [IdleLands/IdleLands#379]
It's not everytime, but I believe being in a party makes my game to stuck. Usually the last choice I get is "Would you like to leave your party?". The game freezes after that. I observe this issue last 4 days.

I have to refresh / reload, party is disbanded, I am solo. Maybe it's because someone (or everyone) leaves the party?

My character's name is Reloecc. I have no more informations about issue yet, I am sorry..

**Comment by seiyria** [comment]
The game probably disconnects and crashes. This happens a lot, and we're trying to fix it. Sorry about that.

**Comment by Reloecc** [comment]
Ok, thank you.. I am sorry. I felt like it's party related - so I want to inform you :)

**Comment by seiyria** [comment]
Not a problem. It's a tough problem to fix since it affects literally everything.
