### ISSUE TITLE
badges insertable into websites

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#41]
"create a badge" -> 
- name
- title(?)
- stats
- class
- class image (maybe)

**Comment by seiyria** [comment]
Given how fast the adventure log rolls, I don't think that'd be possible. I'd have to update the badges once a day and push the images to a CDN to make this work, since the game does go down frequently for updates. For now, I'm going to have to say no.

**Comment by An00nymushun** [comment]
Well then, I see people copypasting adventure logs in the chat, how about a send to chat / share button and a badge that has the last shared one

**Comment by seiyria** [comment]
If anything, I think I would add a social share button to them in the adventure log, to share to facebook/twitter. I'm not sure yet, though. I guess it would be a lot easier if I store a quote so I will consider that avenue as well.

**Comment by seiyria** [comment]
closing this for now as this likely will not happen
