### ISSUE TITLE
Tiles store the name of their region

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/IdleLands#426]
When maps are first loaded, each Map creates a region array and [assigns each tile a region name](https://github.com/IdleLands/IdleLands/blob/b0e132db50e4d9865e06af863a7ab748059bf399/src/core/world/map.js#L51). Fortunately, the V8 engine is smart enough to make these into a reference to the string.

However, removing these will mean more load on the CPU since it means computing the region each time it's needed. Unfortunately, the region name is needed every step to increment the region statistic.

**Comment by seiyria** [comment]
ehhh. I would like to handle this but v8 is smart enough to make references as you said, for now I'll just close it in the interest of housekeeping.
