### ISSUE TITLE
Pets altering xp gains from combat

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#428]
If a player chooses to not level up a pet (especially one with a high battle join chance,) or has a pet equipped with a low max level, it can reduce the party level by enough to guarantee the full 11% xp on a win and 0% xp lost on a loss.

For instance, a party of one level 90 and three level 50s has a party level of 60.
With a level 1 pet thrown in, they have a party level of 48.2.

That's a big enough difference that two of those parties, one with a pet and one without, couldn't even be matched together, if pets counted for combat matching. And yet, if they fight and the party with the pet wins, they get *11%* of their max xp and if they lose, they lose nothing, despite being effectively the same party. The party without the pet *only* stands to lose from this combat; they cannot gain anything no matter what, despite the enemy being exactly their level (plus one incredibly weak pet that has, at best, a miniscule effect on the combat.)

My suggestion (and I'll submit a PR to this effect, since Sei isn't here to dismiss/concede my point in person,) is that party level not include non-players. That way the aforementioned party (with party level 60 sans-pet,) can't be matched with a level 50 party and still come out with favorable gains/losses. I can't guarantee that this won't have any side effects, because I don't really know how to search for party.level, since the search ignores periods and I'm sure not all party instances are named "party."

I had considered the possibility of moving `this.endBattleBonuses();` before `this.cleanUp();` (from [here](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/battle.js#L206-L208)) but I assume it's intentional for pets to get xp/gold through combat (or that if it's not, you'll want to leave it in,) and I don't really know the full implications of the `persistToDb(this);` that happens between them, so I figured it would be best to find another way.

**Comment by seiyria** [comment]
Pets should get XP and gold. I'm fine with them not counting to remove the
incentive to keep them low or mid level.

**Comment by Anexes** [comment]
Can I close this issue or is there something I missed?
My PR is [here.](https://github.com/IdleLands/IdleLands/pull/429)

**Comment by seiyria** [comment]
Feel free.
