### ISSUE TITLE
Player logged in with Facebook as per usual, created new char over old char?

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#430]
Name: Bobox
Old name: Bobo

Says he always used Facebook to log in to Bobo, had trouble logging in with Facebook yesterday, then today logged in with the same Facebook and created a new character, Bobox.

I've heard plenty of people say they ran into trouble when trying to log in with Facebook, but this is the first time I'd heard of someone overwriting their character. Ezioo says the same thing happened to him, and that his old name was Eziomo.

I've seen both Bobo and Eziomo around, so I know they existed at some point.

I know it sometimes shows the character creation screen when you try to log in, especially when the server's slowing down; is this simply a matter of them creating a new character before the server catches up and tells them they already have one?

Either way, I'm not sure how data is stored, so I figure their old characters are just kinda hidden somewhere, but I have no idea. Have their old characters been completely overwritten? If they're retrievable, I'd like to let them know.

**Comment by seiyria** [comment]
It shouldn't allow a creation, I'm pretty sure there's a unique constraint on login info. I guess I'll double check that.

The only reason this happens is due to lag, because they sit on char create.

**Comment by Anexes** [comment]
Ok. And I apparently forgot to hit send last night, so if it's relevant, I hope it's not too late; Ezioo says that if he has to choose between Eziomo and Ezioo, he'd rather keep Ezioo.

**Comment by seiyria** [comment]
this has happened again and there definitely is some hokey shit going on, if there is a new player flag it needs to be checked when creating a character, or something needs to happen to fix this

**Comment by seiyria** [comment]
this should no longer be possible as the game will switch to a state where it's trying to connect, disallowing this from happening.
