### ISSUE TITLE
Unstoppable and Sponge don't give the right amount of hp?

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#473]
I triple-checked to make sure my numbers were right. I assume that with tier 5 of both Unstoppable and Sponge, I should have 10% more hp, but I'm only getting about 4.3%. I've been trying to figure out how it's calculating that number, but the closest I can get is hp_1.02_1.02.

I changed from Archer to Fighter and now I find that I'm getting about 12% more hp, instead of the expected 10%. I have no idea what's going on. Is it 'cause most of my hp was coming from dex? Do Unstoppable and Sponge increase your "hp" by increasing your con or something?

This is just something I noticed and don't understand: [Stat-calculator](https://github.com/IdleLands/IdleLands/blob/master/src/shared/stat-calculator.js#L92-L101) doesn't seem to account for tiers, and [Sponge](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/Sponge.js#L21) and [Unstoppable](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/Unstoppable.js#L21) don't seem to account for tiers either (unlike [PKer](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/PKer.js#L19-L27), for example.) This same thing seems to apply to [Effective](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/Effective.js#L21).

Looking now as a Fighter, I'm getting about 1.3% more mp than my calculator says I should be getting (sans-achievements,) but I have Effective tier 9, which claims to be +9% mp. Could it be that there are two [baseValue](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/Effective.js#L8-L21)  variables? (Top and bottom lines of highlighted area.)

**Comment by seiyria** [comment]
Actually, stat-calculator should not deal with tiers at all. I'll fix sponge, unstoppable, and effective.
