### ISSUE TITLE
Party members can't follow leader onto a restricted tile

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/IdleLands#477]
A party member tries to [follow](https://github.com/IdleLands/IdleLands/blob/a6a6d11d764f76ba2b9f50478d094936b1f4775c/src/plugins/players/player.movement.js#L183-L185) their leader onto a [restricted](https://github.com/IdleLands/IdleLands/blob/a6a6d11d764f76ba2b9f50478d094936b1f4775c/src/plugins/players/player.movement.js#L38-L57) tile. This gets [repeated](https://github.com/IdleLands/IdleLands/blob/10c8e99706377dc85f21a6624be0fe34440f4a8b/src/plugins/players/player.js#L248-L258) until the error gets logged.

Possible fix: Use the overrideFollow argument for the loop's [pickRandomTile](https://github.com/IdleLands/IdleLands/blob/10c8e99706377dc85f21a6624be0fe34440f4a8b/src/plugins/players/player.js#L258) if the party member can't follow the leader. Note that you may also want to supply an actual index for [pickFollowTile](https://github.com/IdleLands/IdleLands/blob/a6a6d11d764f76ba2b9f50478d094936b1f4775c/src/plugins/players/player.movement.js#L184) instead of the default 0.

The way [canEnterTile()](https://github.com/IdleLands/IdleLands/blob/a6a6d11d764f76ba2b9f50478d094936b1f4775c/src/plugins/players/player.movement.js#L38-L57) is structured also means that only one restriction can ever be active for a tile. It will return without ever checking the second.

**Comment by seiyria** [comment]
this is intentional BUT I don't have a good resolution. I don't want people getting dragged through if they don't have the right resources to be there. perhaps a forced party leave is a decent choice in these circumstances.
