### ISSUE TITLE
spell._emitMessage returns string, doesn't emit anything

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#478]
Compare [spell._emitMessage](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/spell.js#L90-L92) with [effect._emitMessage](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/effect.js#L23-L28).

spell._emitMessage should format the string (which it does,) then hand it to [battle._emitMessage](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/battle.js#L45-L50) (which it does not.)

**Comment by KennethShen** [comment]
It doesn't need to. `cast()` deals with[ passing the message](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/spell.js#L136) to `battle._emitMessage()`

**Comment by Anexes** [comment]
It's accounted for in spell.js, but, at the very least, not in Summon.js. [This line](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/spells/Summon.js#L76) does nothing. As it is, `spell._emitMessage` isn't emitting anything, it's just formatting a string and returning it.
