### ISSUE TITLE
Bonecrafting a player who was already bonecrafted sets $prevParty to the enemy party

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#479]
[Bonecraft](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/spells/Bonecraft.js#L27) doesn't check if you've already been bonecrafted. If you get bonecrafted a second time, $prevParty is set to the enemy party and when the battle ends, you get put back on the enemy team.

**Comment by Anexes** [comment]
My plan to fix this was to replace `$prevParty = target.party;` with `if(!$prevParty) { $prevParty = target.party; }` so a player could be bonecrafted many times, but would always return to their original party.

@seiyria You asked me to submit a PR, so I want to make sure I understand how you want things to be.

You said you only wanted someone to be targeted by bonecraft if $prevParty wasn't set (meaning they hadn't been bonecrafted already.) Should I change spelltargetpossibilities.anyEnemyDead and spelltargetstrategy.randomDeadEnemy so they ignore bonecrafted enemies? Bonecraft is the only spell that uses them, so it would work fine, but if they were ever used by another spell in the future, they might not act as intended. Should I instead make new functions just for bonecraft? (For instance, spelltargetpossibilities.anyEnemyBonecraftable and spelltargetstrategy.randomBonecraftableEnemy.)

You seem hesitant to accept code that I've written if it changes more than a line or two, so if you still disagree with my original plan, you might want someone else to do this. I'd be happy to help (once you answer the above questions,) but I understand if you'd prefer to wait for someone else.

**Comment by seiyria** [comment]
Yes, that's a start but you have to add it to the spell target possibilities as you suggested. It should be added as a new strategy and &&'d with the old one.

I'm not hesitant to accept code from you, I'm hesitant to accept untested code.
