### ISSUE TITLE
Lost my character??

### ISSUE THREAD

**Issue by JourneyOver** [IdleLands/IdleLands#48]
So started playing last night and went to bed and everything was working fine, woke up today and noticed game hadn't done anything for several hours so I go to do a refresh, queue game not loading completely at all (as in the game loads but it just sits there half blank) stats aren't showing up, clicking to other various spots on the webpage to go to chat and such don't work, nothing is working. So I go to logout of the game and log back in in hopes that it would resolve the issue, but to my demise it does not and it's giving me the create a new character screen even though I already have a character on the game.

refresh page couple times and it still shows create a new character screen, sometimes it'll switch over to the actual game like I have my old character but the game is stuck loading various things again so I refresh again and get hit with create a new character all over again..

WTH is going on :c

**Comment by seiyria** [comment]
What is your character name?

**Comment by seiyria** [comment]
Anyway, if you can get in, your character isn't lost. The game is under stress and it's attempting to be resolved.
