### ISSUE TITLE
Opencombat links show empty log

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#481]
New tab opens, I'm not logged in on that tab, but the log is empty. The share button is there, along with all the buttons on the bar up top, the log is just empty.

To avoid all these problems, is there a way to make it so combat links open in the same tab? Could you make the client recognize a certain kind of non-URL text (example: "#C-1476211456530") in chat as a combat link, and have it redirect the page to the combat log? Just like when you click the [View Battle] link in the adventure log? That way you can stay logged in as if you were just swapping to Overview or something, which seems like it would solve the problems we've been seeing.

The server's under far too much stress to worry about parsing every message, trying to find the text, but could you have the client look through each message as it's received, and swap it out then?

**Comment by seiyria** [comment]
post back if this is still a problem, I feel like the server stress caused it

there's no real problem with "parsing every message [...]" because it's all sent as one big blob

**Comment by Anexes** [comment]
@seiyria Is that a no on making the combat logs open in the same tab?

**Comment by seiyria** [comment]
for now, yes.

**Comment by Anexes** [comment]
@seiyria I had that problem with a combat log showing up empty earlier. Looks like Lona had the same problem. It worked when I closed it and opened it again. Lona said he refreshed the log and it worked.

**Comment by seiyria** [comment]
opencombat no longer exists
