### ISSUE TITLE
Add an option to disable map updates for the client

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/IdleLands#485]
Give some mercy to the server.

Allow players to opt out of map updates if they don't want to know where other players are.

Related: IdleLands/Play#123

**Comment by seiyria** [comment]
I would probably implement this as an ENV variable, the client doesn't need to opt in or out.

**Comment by KennethShen** [comment]
I meant for it to be more of a player choice so that only the players that want the updates will get them.

Disabling it globally works too.
