### ISSUE TITLE
Feed Ally can target players with full hp and maybe casts unnecessarily?

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#489]
Is this intentional? The main point of the spell seems to be a heal, but it keeps getting used on players with full health. I know it's got the cookie buff too, so I suppose that could be why, but the cookie really seems like a secondary effect.

And during the cookie buff section ([here](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/spells/FeedAlly.js#L18),) it casts twice, one immediately after the other. It looks like the first cast is just for the message, because you can't really pass both players and only affect one; is there any way to consolidate that? At this point, the target has already been healed, so this cast doesn't need to do anything to them. They shouldn't need to be passed in, I think they're just used in the message. Could we use `${target.fullname}` in the message, and pass the caster into the cast where the cookie effect is applied?

**Comment by seiyria** [comment]
It is not currently able to be consolidated.

**Comment by Anexes** [comment]
@seiyria Ok. Is it intentional that it can target full-health players?

**Comment by seiyria** [comment]
Yes. It is a buff too.
