### ISSUE TITLE
Minions don't get proper stats, dracolich is removed from combat after 1 death

### ISSUE THREAD

**Issue by JoeSyr** [IdleLands/IdleLands#496]
Seen in rounds 1-2 here: https://justpaste.it/zjie

**Comment by KennethShen** [comment]
It's a slight conflict between normal summon behavior on [death](https://github.com/IdleLands/IdleLands/blob/fdbdb9c428e94dfb726f229c0678191ae8a811da/src/plugins/combat/spells/Summon.js#L80-L83) and Lich behaviour on [death](https://github.com/IdleLands/IdleLands/blob/6165e380fb8b74bd07b87201d991bf4662148e84/src/core/professions/Lich.js#L36-L42).

**Comment by JoeSyr** [comment]
Changed title to reflect that all minions seem to be getting low stats, not just dracolich. Skimmed over the others the first time around.

**Comment by Anexes** [comment]
@JoeSyr @KennethShen I believe this was fixed with PR #497, does anyone object to me closing the issue?

**Comment by Anexes** [comment]
@JoeSyr @KennethShen I'll take that as a no.
