### ISSUE TITLE
Negative xp after winning a battle.

### ISSUE THREAD

**Issue by Anexes** [IdleLands/IdleLands#498]
https://justpaste.it/zk1v

Avion pointed out that NeweR got -2 xp for winning.

**Comment by Anexes** [comment]
Tahu says it's an edge case where the xp given by combat is 0, which bypasses the isPositive check.

**Comment by Anexes** [comment]
Possible to turn negative xp into positive xp with TH + greedy? Like when losing a battle?

**Comment by seiyria** [comment]
yes, th is -90%, greedy is -15% I believe

**Comment by seiyria** [comment]
yes, th is -90%, greedy is -15% I believe
