### ISSUE TITLE
Make explorer useful and scale 

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#519]
Static 3 XP isn't particularly useful. Maybe +0.2 per level and minus the same as a percent of stats lost

**Comment by Anexes** [comment]
-20% stats at level 100? That's a pretty significant amount. And I don't know how useful 20 bonus xp would be. Maybe it could be a % increase to xp? That way it would scale better for higher levels.

I probably wouldn't trade 20% stats for 20% xp though. I'd trade 10% stats for like 20% xp. That'd bring the xp from combat up by like 1% of your max xp.

**Comment by seiyria** [comment]
The numbers are of course negotiable, but the idea is the same. I don't
want people writing off personalities at certain points. I'd like to make
them always useful.
