### ISSUE TITLE
Can't equip item with negative score, "too powerful"

### ISSUE THREAD

**Issue by JoeSyr** [IdleLands/IdleLands#529]
See for example, trying to equip item at bottom of list: http://i.imgur.com/a0OYuLV.png

Maybe only occurs when taking from pets? Or perhaps nobody's been trying to equip the objectively terrible items that usually come into their choice logs.

**Comment by seiyria** [comment]
it would occur at any point because I think it requires score > 0

will leave tihs open regardless

**Comment by seiyria** [comment]
closed because you can no longer get items with a negative score, they are just autosold
