### ISSUE TITLE
Achievement description inconsistencies

### ISSUE THREAD

**Issue by LucifaZ** [IdleLands/IdleLands#53]
Achievements which give a 5% increase (Consumerist, Golden etc.) show incorrect values in the rewards description due to using the toFixed() function which rounds it to the nearest '1' value:

`itemValueMultiplier: (tier*0.05).toFixed(1),`

Additionally, the Consumerist achievement displays that the increase to DEX is 0.01% but I think it should display 1% (one or the other).

`const rewards = [{
      type: 'stats',
      itemValueMultiplier: (tier*0.05).toFixed(1),
      dex: (player, baseValue) => baseValue*0.01*tier,
      dexDisplay: `${tier}%`
}];`

`desc: "Sell items for ${tier*5}% more for spending ${baseValue * Math.pow(10, tier)} gold, and gain +${tier*0.01}% DEX.",`

**Comment by seiyria** [comment]
Thanks, you are correct on both counts. I'll fix this.

**Comment by LucifaZ** [comment]
Just found another inconsistency for the achievement [Sponge](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/Sponge.js)

The description shows incorrect values for the required amount of damage taken. It is showing values 10 times too high:

`desc: "Gain +${tier}% HP and +${tier*20} CON for taking ${baseValue * Math.pow(10, tier)} damage."`

I believe this should be similar to [Unstoppable](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/Unstoppable.js)

`desc: "Gain +${tier}% HP and +${20*tier} STR for dealing ${baseValue * Math.pow(10, tier-1)} damage.",`

**Comment by seiyria** [comment]
You are correct there as well.

**Comment by seiyria** [comment]
If you find anything else, don't hesitate to let me know!

**Comment by LucifaZ** [comment]
I think the [Consumerist](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/Consumerist.js) Achievement is still showing incorrect values for the DEX increase in the description (_should be 1% but showing increase of 0.01%_):

`desc: "Sell items for ${tier*5}% more for spending ${baseValue * Math.pow(10, tier)} gold, and gain +${tier*0.01}% DEX.",`

**Comment by seiyria** [comment]
you're right, I changed everything but that, haha.

**Comment by LucifaZ** [comment]
The description for the achievement [Golden](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/achievements/achievements/Golden.js) shows an error for the amount of gold required.

**Case**: Tier 2 requires player to have a `value`of 200,000 but the description will display 2,000,000.

`desc: "Sell items for ${tier*5}% more for spending ${baseValue * Math.pow(10, tier)} gold, and gain +${tier}% DEX.",`

I think it should be: after `Math.pow(10, tier-1)`

**Comment by seiyria** [comment]
adjusted!
