### ISSUE TITLE
Game Broken/Not Updating

### ISSUE THREAD

**Issue by zombotz** [IdleLands/IdleLands#530]
Just started yesterday.  Worked fine. (Except when Seiyria tried to trigger a custom very bad item drop but nothing happened)

This morning it loaded, worked for maybe 15 mins. Its been 2.5 hours now, no updates except in the chat.
So I go to other tabs, and they are empty (Pet, Achievements, Collectables). If I force reload (CTRL-F5) on a page (eg. Pet), it loads (eg. pet rock), but another tab goes empty (eg. Statistics). There is a pop-up on top-right that says I'm logged in and welcome back when I refresh.

Chat seems to be working, but I can't tell if they can't see my messages, or are ignoring me.

in-game name: zombot
Chrome on Win 7 64-bit

**Comment by seiyria** [comment]
Lots of things are probably suffering due to the load of the game, unfortunately. It works fine on local, so this is just an issue of the server being overloaded.

**Comment by zombotz** [comment]
About 6 hours now, but others still seem to be enjoying it.

Oh well, guess its not for me.

**Comment by qveck** [comment]
Same for me, map and events not updating.
2 hours now and nothing, the "Statistics" page is empty as well as my Achievments and Collectibles.

**Comment by seiyria** [comment]
Generally this means I just have to reboot the game, which I will do now. Past that, there's not a lot I can do.
