### ISSUE TITLE
mp/flip the bit/spell costs

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#531]
with the recent mp change, flip the bit is kinda nasty. I would posit that mp should grow similarly to hp.

I also think that all spells should move to a percentage based cost (where static things like mpregen still exist). there should be a way to make spells fluctuate so you aren't always losing 1% for a spell and gaining it back right away. Maybe it should be -% and a static amount, or something.

**Comment by Kookiecraft** [comment]
I'm not really sure how to go about mp balancing. Once a character runs out of mp, they'll most likely alternate between Attack and their lowest mp cost skill. Is that the intention?

**Comment by seiyria** [comment]
This [the original issue] has actually been fixed, I believe, with mp having a 6x multiplier like hp. 

Something that could tweak it is allowing for spells to cost a % of your mp, though, which would make your  mp more valuable.

I'm undecided on how to proceed here, though.

**Comment by seiyria** [comment]
If anything is to be done, it should be a new issue. For now, we'll call this good.
