### ISSUE TITLE
Select Element Style Truncates Text on Settings Tab

### ISSUE THREAD

**Issue by Vandivier** [IdleLands/IdleLands#539]
The bottom portion of "g", "y" and similar letters is cut off by the height allowed in the select elements. For example, see the Settings Tab and see Light Theme, Majestic, etc.

I think it's a general problem, but here are my specs at run time:
FireFox 49.0.2
1920*1080 monitor, Asus MX279, 27", fullscreen

**Comment by seiyria** [comment]
re-recorded here: https://github.com/IdleLands/Play/issues/129
