### ISSUE TITLE
Gold/xp multipliers from personalities stack inconsistently

### ISSUE THREAD

**Issue by JoeSyr** [IdleLands/IdleLands#544]
When the sum effect of treasurehunter and seeker/greedy is >1, the outcome is sometimes set to 0 to prevent turning gains into losses. But in the case of these multipliers being applied to a loss, it seems to take the absolute value of the sum before multiplying, presumably to avoid turning losses into gains. This makes it a bit counter intuitive to try and interpret how these things work together.

Treasure hunter on its own will mitigate losses just as much as it lowers gains, the end result will be x*.1, whether x is positive or negative.
Treasure hunter + seeker will drop all gold gains to 0, but reduce gold losses by slightly less than treasure hunter on its own. The result is a x*.15, but only for negative values of x.
Likewise, treasure hunter + greedy works the same way for xp.

I would suggest that either losses should be zero'd, or gains should end up with a .15 multiplier as well, either way it ought to be consistent.

(edited to account for xp working the same as gold, and an attempt to present it all a bit more clearly)

**Comment by Anexes** [comment]
@JoeSyr @seiyria I put in a PR that should prevent xp/gold from flipping signs. I recommend looking at it before accepting it in case there are any glaring mistakes. It runs fine and players gain xp/gold as normal, but I'm having trouble getting personalities to work on my server. I think I know why, but it's fighting me, and I'm too tired to go digging around.

If someone who knows mongodb better could check if it works, that'd be really helpful. (Enable greedy + TH on everyone and everyone should get 0 xp from all combats/events. The math is the same for gold, so if it works with greedy + TH, it should work with seeker + TH.)

**Comment by JoeSyr** [comment]
Patch looks good to me, closing.
