### ISSUE TITLE
Typo on Cleave.js

### ISSUE THREAD

**Issue by LucifaZ** [IdleLands/IdleLands#55]
I believe there is a type on the function `getPercent()` in the [Cleave.js](https://github.com/IdleLands/IdleLands/blob/master/src/plugins/combat/spells/Cleave.js) file

`static shouldCast(caster) {
    return caster._special.gtePercent(30);
}`

**Comment by seiyria** [comment]
Nope! Actually, `gtePercent` is "greater than percent"

Don't let that get you down though, I like issues in the tracker so keep posting your findings.
