### ISSUE TITLE
Suggestion: op command to auto-refresh client end (Play)

### ISSUE THREAD

**Issue by sidawson** [IdleLands/IdleLands#550]
It occurred: It would be relatively trivial to add an op command to refresh/reload the client side in (say) a minute (setTimeout etc), if there was going to be a push of a new version of Play.

Minor thing, but more reliable than asking all users to refresh manually.

**Comment by seiyria** [comment]
Already documented in #51. I decided against it - trivial, but interrupts the user and is bad UX as a result.

**Comment by sidawson** [comment]
Fair enough. And yep, good point.

Thanks for explaining.
