### ISSUE TITLE
races

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#558]
Allow for people to have a race (much like a title) that acts like a profession (skill, stat buffs).

A few races would have to be thought of, acquisition methods would need to be considered, and overall impact should be thought about.

I'm on the fence about this currently.

**Comment by sedgwick** [comment]
I like the idea, but think that with races should also come some race sprites. If you unlock dwarf, you'll probably want to have the option to look like a dwarf.

**Comment by seiyria** [comment]
.. right. that's a problem. and we have genders already. I think this came up last time as well.
