### ISSUE TITLE
Necro battles can cause error teleports

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/IdleLands#569]
http://pastebin.com/j4XqjDNJ

In at least a few mentioned battles, if a team ends up with no players remaining due to being resurrected to the enemy team then the battle errors out and teleports you to spawn. Probably has a really high chance in solo parties that lose, but a full party would have a better chance of not having everyone resurrected before the battle ends.

seiyria> bounty 2000 for determining exactly why people get teleported away

**Comment by sedgwick** [comment]
Another look at a failed necro battle.

http://pastebin.com/0ip74uj4

**Comment by selicate** [comment]
Teleporting still happening post-fix. [http://pastebin.com/yP1xrJnX](url)

**Comment by seiyria** [comment]
Yep, we know.

**Comment by kinderghast** [comment]
Potential Teleport in this Battle, don't know if the log helps at all but data is data

[PasteBin: Battle_1501337027701_Potential_Teleport
](https://pastebin.com/QKUyuEu0)

**Comment by sedgwick** [comment]
Bonecraft is no longer an accessible spell, which "fixes" this bug.
