### ISSUE TITLE
Buy festivals with ILP 

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#57]
- 35 ILP - 30% base stats - 3 days
- 50 ILP - 30% XP - 3 days
- 65 ILP - 30% Gold - 3 days

You can only have one of these festivals at a time.

**Comment by boozledorf** [comment]
- 100 ILP? - Reset all cooldowns (Treasure, forceEvent [gold piles, item piles, Merchants, etc.], and Bosses).  May be a scroll so you can hold onto them.  May also be available as very rare loot from astral gate?
