### ISSUE TITLE
Gear with requirements other than item score

### ISSUE THREAD

**Issue by boozledorf** [IdleLands/IdleLands#591]
Gear that needs certain requirements to equip other than item score, like achievements, stats, current profession, etc.

Example: "of the Mage Master" (large boosts to INT / MP / MPRegen, for example) -- can only be equipped after getting the Mage Master achievement.

**Comment by JukeDragh** [comment]
Didn't Kookie add aReq?

**Comment by seiyria** [comment]
Yes.
