### ISSUE TITLE
altars

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#602]
altars should:

* have an internal timer so they can't be spammed
* give a random event from a AltarBlessEvent or AltarForsakeEvent (which would in turn do any of the blesses, any of the forsakes, maybe bless does enchants and forsake can do fate pools, rarely).
* forsake altars should have a small chance of doing good, and vice-versa

**Comment by sedgwick** [comment]
Altars have made their way into the game in an alternate form. Red altars cause forsake item events, while blue altars enchant items.
