### ISSUE TITLE
Lost gold feeding pet

### ISSUE THREAD

**Issue by EvoGeek** [IdleLands/IdleLands#603]
I had 20+ million. I fed my pet. I went to buy my broom it's final upgrade, increase max level for 20 million. Couldn't. Looked at my gold, 0.

Mentioned it in chat, said it was a bug in the client version I was on. I've refreshed to latest client.

Can you assist with returning my gold?

IGN:  EvoGeek

**Comment by seiyria** [comment]
yes, I will give you gold back. update your frontend version (refresh).
