### ISSUE TITLE
Teleports onto chests do not activate them.

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/IdleLands#606]
Other Interactables will activate by TP, like a boss battle, but a chest will not trigger a statistic update or offer an item.

It's possible something might be up with collectible TPs as well, though I only have 1 TP that I can test and you can see here it doesn't show the proper region: https://puu.sh/uBYny/465fa665a4.png

**Comment by seiyria** [comment]
I think it is activating, but as per usual with treasure chests, it's not necessarily going to give you anything. I will change this behavior to at least say you visited a chest, however.
