### ISSUE TITLE
Equipment with negative base score gets -% from upgrades.

### ISSUE THREAD

**Issue by xchronox0** [IdleLands/IdleLands#608]
I found an item called +1 Sticker Book which has a base score of -7. It's current score is 343, thus, being at -4,900%. It will never reach it's upgrade cap, thus being capable of infinite upgrades.
![image](https://cloud.githubusercontent.com/assets/5298387/23888208/0fc67d90-085d-11e7-9a69-4df04aeea770.png)

**Comment by seiyria** [comment]
That's fine. People will not hold onto these items for that long. I'll eventually push a patch to make them unblessable/etc I guess.
