### ISSUE TITLE
can apparently fight yourself

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#612]
https://gyazo.com/5ff0a1315d378935b89cb340656cff6f

bounty 2000 ilp

**Comment by nugarin** [comment]
FYI. I left myself logged in at another comp. Could it be that it somehow relogged in and I had two sessions open?

**Comment by seiyria** [comment]
Shouldn't. You can't interact with yourself from another server (if that was the case) and you log back in to your character if you log into the correct server.
