### ISSUE TITLE
Collectibles: Mark currently owned vs owned in previous ascensions

### ISSUE THREAD

**Issue by Takeces** [IdleLands/IdleLands#62]
Currently collectibles only display "Owned!" if they have ever been owned. It should be distinguishable if one collected it in the current run.

I've thought of something like "Owned!" vs "Seen!"

**Comment by boozledorf** [comment]
Please also sort collectibles in the Collectibles pane in Accomplishments so you can see at a glance which ones you have this ascension vs which ones you've only had in the past.

**Comment by seiyria** [comment]
second comment moved to #61
