### ISSUE TITLE
Feed Max Can Consume Disproportionate Amount of Gold

### ISSUE THREAD

**Issue by LucentGlow** [IdleLands/IdleLands#620]
Occasionally using the Feed Max button to level your pet will consume an extremely large quantity of gold.

**Comment by nugarin** [comment]
Happened to commiehunter as well. do not remember details

**Comment by TryHardHusky** [comment]
Also had this problem

**Comment by seiyria** [comment]
I need to know what pets, what level they were at, how much gold you lost,
because as far as I can tell this is working correctly.

**Comment by JukeDragh** [comment]
I lost 48,000,000 by feeding the Chimera Dragon from 168-175.

**Comment by JukeDragh** [comment]
My calculation says it should have been 846,964

**Comment by LucentGlow** [comment]
I lost around 2mil leveling my pet from 46 -> 50, should've cost around 400k
