### ISSUE TITLE
guild changes

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#627]
With guilds implemented, there are likely to be a few straggling features that may need to make the cut. Here are some on the table:

* Guild Buffs
* Guild Parties
* Guild v Guild PvP (req new building: barracks - you say to attack a particular guild, starts a big fight with all involved people)
* No PvP between guild members (this should be an option)
* Tavern could have an action to form a guild party.
* Guild TP should unlock more destinations as it levels up
* Item Crafting - take resources and make items out of them

What else?

**Comment by Laciacrus** [comment]
Guild Wars

**Comment by JukeDragh** [comment]
A guild pet that joins guild parties
Guild trading...? (Marketplace or between members)

**Comment by seiyria** [comment]
Probably not @ guild pet. Guild trading will come with the guild hall.

**Comment by yourtoilet1** [comment]
a guild hall in astral town that has a tp back to norkos and a tp to astral plane that requires astral sandwich
ALL HAIL THE ASTRAL SANDWICH

**Comment by seiyria** [comment]
there will not be a guild hall in astral town because it would allow people to skip a lot of the content in the game.

**Comment by yourtoilet1** [comment]
thats why it would require astral sandwich which is an astral plane collectible

**Comment by seiyria** [comment]
I see, I'll consider it in that case.

**Comment by seiyria** [comment]
anything in here that isn't done probably won't be unless a new issue is opened.
