### ISSUE TITLE
First time Equip Item (Player) is closed when Pet Items is opened snaps page to top

### ISSUE THREAD

**Issue by LucentGlow** [IdleLands/IdleLands#646]
Opening opening the Items tab and click Equip Item (Player) and closing it (Equip, Sell, or Close buttons) causes the page to snap to the top of the page. Only occurs the first time the button is closed. Changing to a different tab and then back to the Pet tab causes it to occur again. Changing to Pet Overview does not.

**Comment by seiyria** [comment]
moved to https://github.com/IdleLands/Play/issues/221
