### ISSUE TITLE
toggling Feeling Lucky on increases xpForsake rates significantly (?)

### ISSUE THREAD

**Issue by Kookiecraft** [IdleLands/IdleLands#650]
I wasn't getting any xpBless, itemBless, or itemForsake events with Feeling Lucky on. I was, however, getting a lot of xpForsake events. I lost count after 23 xpForsake events with a few battles and findItems mixed in, but there were definitely no xpBless, itemBless or itemForsake events when i had Feeling Lucky on.

For a quick sloppy test, I turned off Feeling Lucky, and voila I was getting xpBless, itemBless, and itemForsake events again. This might or might not affect some of the rarer events as well - itemEnchant? 

Other personalities that were on at the time: Drunk, Solo.

It might be notable that I did not lose any xp from these xpForsake events according to the xp listed under Vitals in Overview. I tried to see if this was the case without any personalities on, but I didn't get any xpForsakes in the span of 2 hours.

**Comment by seiyria** [comment]
well, it doesn't touch xpForsake explicitly: https://github.com/IdleLands/IdleLands/blob/034ee4b4a08bf37cc16003600651a333bd508db0/src/plugins/personalities/personalities/FeelingLucky.js#L13-L15

What is probably happening is that it's removing these two events from the pool, making it more likely to choose xpForsake (or anything that's not those two events). This is a byproduct and may or may not be addressed, but for now I guess this is working as intended.

**Comment by Kookiecraft** [comment]
With the weights the way that they are, wouldn't you expect xpBless to happen 3 times as often? With feeling lucky on, xpBless never happened.

**Comment by seiyria** [comment]
I don't think so. It just cuts them out of the probability weighting. If you can find anything weird regarding this, definitely let me know (we can reopen this or whatever needs to be done) but it seems like an unintentional side-effect for something that is definitely intentional
