### ISSUE TITLE
Choice log contains more than max number of choices

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/IdleLands#682]
There was a recent change that added ["Pet" to a FindItem](https://github.com/IdleLands/IdleLands/blob/cd96c4a8eb30df542fe3c5b9b28c0043e0718cec/src/plugins/events/events/FindItem.js#L61) choice. 

When combined with the Indecisive personality, the Pet option can be [selected](https://github.com/IdleLands/IdleLands/blob/b95af57dfccae878252e588c7635d17c7192a863/src/plugins/players/player.js#L268). If the pet's inventory is full, it will return a [message](https://github.com/IdleLands/IdleLands/blob/cd96c4a8eb30df542fe3c5b9b28c0043e0718cec/src/plugins/events/events/FindItem.js#L80).

The message is a [string](https://github.com/IdleLands/IdleLands/blob/cd96c4a8eb30df542fe3c5b9b28c0043e0718cec/src/plugins/events/event.js#L62-L68) and the [choice will not be removed](https://github.com/IdleLands/IdleLands/blob/b95af57dfccae878252e588c7635d17c7192a863/src/plugins/players/player.js#L285-L287).

**Comment by KennethShen** [comment]
The same problem happens with Affirmer/Indecisive (selecting Yes) and [Merchant events](https://github.com/IdleLands/IdleLands/blob/b95af57dfccae878252e588c7635d17c7192a863/src/plugins/events/events/Merchant.js#L73).

**Comment by seiyria** [comment]
think I got it for real this time
