### ISSUE TITLE
Level up bug (extra lvls)

### ISSUE THREAD

**Issue by MrDamageD** [IdleLands/IdleLands#690]
Today while idling i lvl up, supposedly to lvl 27 (attach1), but my adventurer got lvl 40 written on it, also i think my character stats are upgraded to lvl 40 has well (like str, agi, con etc)

PS- sorry about grammar, english aint native

![idleland lvl bug](https://cloud.githubusercontent.com/assets/25730072/24934212/2d18eb0a-1f12-11e7-82f7-8e0a9d5330f0.png)

**Comment by seiyria** [comment]
I would wager that part of your adventure log is a bit behind. There was a point today where XP gain was +1200% or so, you probably just leveled very quickly.

**Comment by MrDamageD** [comment]
All my logs are has follows:
"
Apr 11, 2017, 11:45:33 PM
«MrDamage, the Sponge» was offered «magic hand» by a wandering merchant, but it was too weak for him.
Apr 11, 2017, 11:43:23 PM
«MrDamage, the Sponge» came across «Hover Boots», but it was too strong for him, so he sold it for 2,110 gold.
Apr 11, 2017, 11:43:16 PM
«MrDamage, the Sponge» came across «Headwings», but it was too strong for him, so he sold it for 2,778 gold.
Apr 11, 2017, 11:43:11 PM
«MrDamage, the Sponge» came across «sword cane», but it was too strong for him, so he sold it for 2,992 gold.
Apr 11, 2017, 11:42:59 PM
The God of Items, Shashkajze, caused a golden, shimmering «Knife-Fists» to appear in front of «MrDamage, the Sponge».
Apr 11, 2017, 1:37:04 AM
«MrDamage, the Sponge» learned how to fly. He acquired 1,755 gold to fly away and never come back. [+1,755 gold]
Apr 11, 2017, 1:33:01 AM
«MrDamage, the Sponge» came across «constitutional girdle», but it was too weak for him, so he sold it for 983 gold.
Apr 11, 2017, 1:31:06 AM
«Wacky Roflcopters» was eyeing up «a paper goatee» and «Hax0rs yet Mailmen» got jealous and starting fighting them!
Apr 11, 2017, 1:28:55 AM
«MrDamage, the Sponge» has reached experience level 27!
"

Was the xp gain during that time? I was actually idling on another device so this one doesnt have the logs updated.

Sorry for threating this has a "bug", didnt knew, was just trying to help.

**Comment by seiyria** [comment]
It's fine. It's hard to tell sometimes.

**Comment by MrDamageD** [comment]
Thanks for the understanding :)

Keep up the great work.
