### ISSUE TITLE
Request: A link to Global Players Page in the Guild Members view

### ISSUE THREAD

**Issue by Aviarium** [IdleLands/IdleLands#701]
In the Guild Members view, can we get an external link for every player, that leads to this players Global Entry?
That would be pretty useful for Guild Management. 

Or maybe fill the almost empty bar with some stats for like guild contribution like yielded ressources and taxed gold for the guild

**Comment by seiyria** [comment]
Duplicate: https://github.com/IdleLands/Global/issues/33

The short answer is that eventually, yes, but not until I work on Global again. Maybe within the next couple of weeks at the earliest.
