### ISSUE TITLE
chests should not allow you to pick up the same item in multiplies

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#707]
if you have an item with that same name in your choices it should be ignored

**Comment by KennethShen** [comment]
[Compare name](https://github.com/IdleLands/IdleLands/blob/f90bd380014da1a415f5fa1e1500b2bd3ffdaa20/src/plugins/events/events/FindItem.js#L54) to `choice.extraData.item.name` instead of `choice.extraData.name`

**Comment by seiyria** [comment]
thanks, my mistake, good catch
