### ISSUE TITLE
Selling Item Nonstop

### ISSUE THREAD

**Issue by gsea4** [IdleLands/IdleLands#718]
It seems like I lost connection to the game and I hit no on the item choice I have to sell it; then I got connection back but somehow I gain gold but item doesn't disappear. And I can click on it to sell it non stop to gain gold now.
<img width="1280" alt="issue with selling item" src="https://cloud.githubusercontent.com/assets/24417642/25456105/94693946-2a97-11e7-95d0-c7f330f2df69.png">

**Comment by seiyria** [comment]
yes, please stop doing that, we already know and are fixing it.
