### ISSUE TITLE
Make the feed pet GUI not openable when the pat cannot gain XP

### ISSUE THREAD

**Issue by Erez224** [IdleLands/IdleLands#729]
Currently (Version v0.11.0-39-g6e3fa0d), you can open the feed pet GUI even though a pet cannot gain XP at the time. Instead, I think you should not be able to open it, because you can't do anything in it anyway, if the pet cannot level up.

**Comment by seiyria** [comment]
Works for me already: http://i.imgur.com/FKJI0dV.png

**Comment by Erez22** [comment]
I did not mean when the pet is maxed out, I meant when the pet is the same level as you and you can't level it up

**Comment by seiyria** [comment]
ok, that's important information. moved to https://github.com/IdleLands/Play/issues/250
