### ISSUE TITLE
vector bosses

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#737]
a possibility could be to scale bosses up by a multiplier based on their level. basically, you could:

* take your level minus the bosses level (if I'm level 250 and the boss is level 1, the difference is 249)
* make some sort of sliding scale (every 10 levels is +10% - the example above would be +240%)
* multiply all boss stats and equipment by that multiplier

* some bosses could be given a vector(x) where X would multiply everything further.

**Comment by JukeDragh** [comment]
Using the method described in 1, use that number to multiply specific stats or modifiers. 
i.e. You are level 200, and they are 50. Difference is 150. 
Monster's Str=1000+100*lvlDif ;Con=2000+500*lvlDif ;Vampire=1+round.(1/20*lvlDif)

It also would be nice if they could drop better gear as a result of the scaling.

**Comment by Kookiecraft** [comment]
Might need to implement specific monster classes so that they have clear weaknesses that certain player classes can take advantage of.... depending on how strong the vector bosses are.

**Comment by seiyria** [comment]
Yes, I think it's only fair that the gear scales with the boss by a similar means.

@Kookiecraft some classes are like that currently. Bitomancer and barbarian are opposites, for example. They might need to be more pronounced but the framework is there.

**Comment by sedgwick** [comment]
It would be good if there was some leeway for when the scaling starts, similar to the 2nd example @seiyria provided. Reason being imagine you are almost able to beat a boss at equivalent level, so you try again a level or two later knowing you are a little stronger. Then the boss is a little stronger amd you still lose. That way there is still a range where you can attempt a boss before it scales with you.
