### ISSUE TITLE
Give item to other pet is malfunctioning

### ISSUE THREAD

**Issue by simdimdim** [IdleLands/IdleLands#740]
when I try to send more than 1 item to the same pet (lets say dolphin) from either the same source (say parrot) or any other pet (say rock for example), it works for teh 1st 'give', but the 2nd one doesn't respond/ does nothing.

(on a side note a future request: 'give all items to other pet')

(using browser : Opera Neon Version 1.0.2531.0)

**Comment by Kookiecraft** [comment]
clientside issue - ionChange now only triggers on an actual change
https://github.com/IdleLands/Play/blob/master/src/pages/pets/pets-items.html#L62

**Comment by seiyria** [comment]
moved to https://github.com/IdleLands/Play/issues/262
