### ISSUE TITLE
Change Combat Pets to store their combat-reward-Gold

### ISSUE THREAD

**Issue by Aviarium** [IdleLands/IdleLands#745]
The main rewards for fights are xp and gold. 
I suggest that all combat based pets get a chance to keep their gold
for example Tier 2 Pets 500k - 1 Milion and Tier 3 Pets 5 - 10 Milion Gold

**Comment by JukeDragh** [comment]
Could you better explain this? All pets get the gold it says they do after winning in combat.

**Comment by Aviarium** [comment]
most pure combat pets have a storage for gold of 0, zero, nada, nothing, nichts - so its mostly wasted when the fight ends

**Comment by seiyria** [comment]
This is intentional. Their goal is to win combat, not reap the rewards.
Your reward is a higher probability of winning combat and a lower
probability of losing.

This is one of the tradeoffs for certain pets and is not likely to be
changed. Doing so would make some pets plainly better than others.

**Comment by Aviarium** [comment]
hmm.. when i brought that issue up in chat, i got told to open an issue for it here. (by you Sei)
there are multiple backsides of pure combat pets:
- no active pet for itemfarming/salvaging/money farming
- divided gold after combat for the party, even being solo, for having a pet out
- gold pet will receive vanishes into nothingness

at least the last part can be fixed by giving combat pets a gold storage. when i see the numbers after a fight, even with stored gold for the pet, you'll still earn less each fight then without it, the cut for multiple partymembers in the fight is higher then the amount a pet receives.

**Comment by seiyria** [comment]
If I remember right the issue was regarding expanding existing pet storage,
not adding it to pets that don't already have it. The original concern was
that pets had 100k storage but were scoring 300k in combat.

I'm all for tweaking those values, but those pets with 0 storage have it
intentionally.

**Comment by Aviarium** [comment]
well, then the issue is obsolete. as it is now, ghostly pets are out only for the sake of leveling them and getting achievements, but not for their effort in fights. 
fighting pets just burn far too much gold to be effective.

how about cutting pets out of the gold-reduction after a fight?

**Comment by seiyria** [comment]
What do you mean, cutting them out?

**Comment by Aviarium** [comment]
When I fight solo without a pet, money gain is about 1,7m gold
If i use a fighting pet its only 940k gold and the pet would have gotten 250k - adding together thats only 1,19m gold
using a pet that does not fight will get me 760k more gold per fight. all i ask for is to get a chance to save that 250k from the pet. there will still be the cost of 510k for using it in the first place. I dont see the need for that double punishment for using a fighting pet.

cutting out the pet, i ment for not reducing the income of the player, just like when having summoned minions.

**Comment by seiyria** [comment]
You don't get double-punished for using a pet. Gold is split between all party members, and pets are party members. It just so happens that they have a gold cap, and presumably you know about that gold cap before going into combat, so you can weigh whether or not it's a good choice to use that particular pet.

The income for the player can be seen as reduced, but it's really not. They get their share as a member of the party, and so does the pet.

**Comment by Aviarium** [comment]
yeah, and thats why all pure fighting pets are rather useless, if its not for the sake of achievements.

either drop them out of being a partymember, or let them keep their gold. Its my pet, fighting my fight and getting the share of my gold - why not keep it? it is still less then without the pet - and thats what you wanted it to be

**Comment by seiyria** [comment]
* Logistically they have to be party members. If they're not, they get no gold from combat.
* They _do get to keep their gold_, in some cases, they just fill up at their gold cap.

As I stated, I am happy to increase the overall gold cap for the pets that have it, but I am not adding a gold cap to those pets with a 0 max.

Just because you don't like fighting pets doesn't mean that they're "rather useless" because some people do need them for boss fights or whatever.

Is that agreeable?

**Comment by Aviarium** [comment]
not really. we talked in the game chat about it 1,5 months ago and you agreed with my point then. I opened the issue cause of that and now its not ok anymore..

**Comment by seiyria** [comment]
ok, well as you probably guessed, it's a bit hard to remember something that old without context. as for me telling you to open an issue, I generally always say that, because it means I can respond to it in my time, without pressure of it being lost in game chat. 

that said, if we can't agree on something then this issue isn't going anywhere.
