### ISSUE TITLE
GuildGambling balancing

### ISSUE THREAD

**Issue by Kookiecraft** [IdleLands/IdleLands#746]
Some problems at high enough tavern levels:
oddsMin passes oddsMax
oddsMin/Max are over 100
multiplierMax becomes approximately 0.1 higher than multiplierMin at all levels after a certain point (this happens relatively early, and I'm not sure if it's intentional)

Some problems at lower tavern levels:
oddsMin grows extremely slowly (intended?)
oddsMax is fixed at 75

Perhaps make these equations logarithmic once someone comes up with something that works.

GuildGamblingChance also scales extremely well with tavern level.

Therealtahu: 

> I'm of the opinion that it's ok to be profitable if you bet wisely, but we don't want anything like yes always, but if odds are above X, double down.

**Comment by JukeDragh** [comment]
Try:
const oddsMin = Math.max(15, 20 + (0.5 * Math.floor(tavernLevel/10)));
const oddsMax = Math.**min**(75, 30 + (0.5 * Math.floor(tavernLevel/2.5))); 

This plus a logarithmic multiplier should produce a more fair guildGamble
It also should be noted that level 100 should probably be the same as normal gamble.

**Comment by seiyria** [comment]
Min should not go over max (this spams my email with errors).

They should never exceed 100 (it is supposed to max at 75).

Min should max out at 50 honestly so it's never always 75% chance.

It should grow very slowly.

**Comment by seiyria** [comment]
I think @JukeDragh already pushed a patch for this.
