### ISSUE TITLE
Diminishing returns for "too many" forceEvent tiles

### ISSUE THREAD

**Issue by Kookiecraft** [IdleLands/IdleLands#752]
This is mainly to discourage repeated drunk stumbling on top of goldBless tiles.

**Idea:**
After a certain number of forceEvent tile events, the amount of gold/xp/anything "rewarded" by any forceEvent tile gets decreased. After some more forceEvent tiles (any forceEvent), rewards decrease further. And so on, until the reward either reaches an extremely low amount or zero. 

Every forceEvent tile will increment a variable by 1. When the variable reaches certain values, the diminishing returns start to kick in. For every X amount of steps that the player takes, that variable is decremented by 1. This could be balanced around some max number of forceEvents that any given player is allowed in one (24 hour) day so that if a player is allowed 500 forceEvents in one day, their variable decreases by 500 over the course of at least two full days. I would personally prefer at least three full days.

This is also relevant to #721

**Comment by seiyria** [comment]
I'm a fan of this. Hell, I'd say 500 every week is pretty rare unless you're really trying. I'd go that high and see how it goes.

This has my blessing.

**Comment by KennethShen** [comment]
Providence Tiles count as forceEvent. Make an exception for them?

**Comment by seiyria** [comment]
I said it was fine not to. The circle of people who do either thing often
do not do the other.
