### ISSUE TITLE
Map does not load

### ISSUE THREAD

**Issue by Zilvai** [IdleLands/IdleLands#761]
Hello there, I have been encountering a game breaking bug where the map does not seem to load. All that appears is a white box and nothing more. Nothing happened in the overview either for several hours.

![mapnotloadingil](https://user-images.githubusercontent.com/30120993/28123228-b47663a6-6720-11e7-9132-ebc3b3b884c4.png)

![overviewincomplete](https://user-images.githubusercontent.com/30120993/28123292-eed20e74-6720-11e7-9acd-e6929610e3b0.png)

Hope this helps to fix it!

- Zilvai

**Comment by seiyria** [comment]
The problem is that you're not logged on, because the server stability is pretty borked. Or, you just registered a new character and that's broken. We know about both of these issues and have no idea why anything is happening. Sorry, hopefully it will work soon.
