### ISSUE TITLE
Player Available Profession Sprites

### ISSUE THREAD

**Issue by sedgwick** [IdleLands/IdleLands#766]
Make (at least) 2 alternate versions of profession sprites available to use as genders for the player. Still TBD on exact requirements, but one version would require a long term investment to earn (Grandmaster + 100k steps as that profession was @seiyria's idea, possibly more steps since a GM of a profession could easily have 100k steps after #762. I feel 1M steps would be fitting for a single profession.) 

The other version would be an expensive ILP version (possibly 25k ILP or 50k ILP each). I feel the ILP version should also have a similar requirement to purchase, but somewhat less than the long term investment option. Maybe make this one have the 100k step requirement (and grandmaster? Or too much?)

Additionally, color options for the alternate professions are red and green like the male and female sprites, or blue like the blue gender sprite.

**Comment by sedgwick** [comment]
ILP version: 25,000 ILP per sprite.
Earned version: Grandmaster of class and 500k steps as class.

**Comment by seiyria** [comment]
Should be implemented to the fullest extent.
