### ISSUE TITLE
Pet soul modify player's Max Item Score

### ISSUE THREAD

**Issue by KennethShen** [IdleLands/IdleLands#773]
[Pet souls](https://github.com/IdleLands/IdleLands/blob/b528527a1787d5fd38632fa6d9f2bcbdf7d430f9/src/plugins/pets/pet.js#L88-L90) include ItemFindRange and ItemFindRangeMultiplier.
When [synced](https://github.com/IdleLands/IdleLands/blob/54409ee8f93ca4bd147800cec4a8a76db4696cbb/src/plugins/pets/pets.js#L200) to the player, this changes their [Max Item Score](https://github.com/IdleLands/IdleLands/blob/f0ccc502cf36e936fc9bc2eaca6085ec36caf1bb/src/shared/stat-calculator.js#L277-L290).

**Comment by seiyria** [comment]
This is intentional. Some souls will provide that utility. If some souls
are too strong they can be cut back though.
