### ISSUE TITLE
refactor: UIService

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#79]
to improve UI performance, all calculated tab headers (quest, pets) should be moved to a service instead of being recalculated frequently.

affected:

- pet gather notification (sidebar, tab)
- pet adventure complete notification (sidebar, tab)
- quest complete notification (sidebar)

**Comment by majoferenc** [comment]
Hi. I would like to work on this issue.

**Comment by seiyria** [comment]
Sure, feel free. I haven't decided what this sort of solution would look like so I can't give a ton of guidance in that regard, but I'd be interested to see what you come up with.
