### ISSUE TITLE
One person party?

### ISSUE THREAD

**Issue by sidawson** [IdleLands/IdleLands#94]
https://puu.sh/r3Nhb/e1754480b3.png

This shouldn't be possible (except for the dummy temp parties used 1v1 battles). I'd had no recent battles.

**Comment by seiyria** [comment]
Duplicate of an earlier bug. This happens sometimes and I'm not sure why or
how to fix it. Well, maybe I am. I think I don't discard solo parties after
bosses, maybe. But even before bosses this was happening so idk

**Comment by seiyria** [comment]
Fix will be check for a solo party on turn, if it exists, disband it.
